name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '4.0.0-beta.1'
      SERVERPOD_PASSWORD_database: 'YQ1x1f-3ZjffntPxOw6AQG0W6yvcTLbT'
      SERVERPOD_PASSWORD_redis: 'bViOMYLTzUmAsl7-yQLz4RZD9II4Q_k4'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.4'

      - name: Start containers
        working-directory: todolist_server
        run: docker compose up --quiet-pull --build -d

      - name: Install dependencies
        run: flutter pub get

      - name: Install Serverpod CLI
        run: dart install serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: todolist_server
        run: serverpod generate

      - name: Run tests
        working-directory: todolist_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: todolist_server
        run: docker compose down -v
